apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: party-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    force-refresh: "{{ now | unixEpoch }}"
spec:
  spec:
  secretStoreRef:
    name: gcp-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: party-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: REDIS_PASSWORD
    - secretKey: SECURITY_JWT_SECRET
      remoteRef:
        key: SECURITY_JWT_SECRET
    - secretKey: SECURITY_PASSWORD_PEPPER
      remoteRef:
        key: SECURITY_PASSWORD_PEPPER
    - secretKey: SECURITY_COOKIE_SECRET
      remoteRef:
        key: SECURITY_COOKIE_SECRET
    - secretKey: METRICS_PASSWORD
      remoteRef:
        key: METRICS_PASSWORD
