apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secretstore
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: eso-gcp-creds
            key: credentials.json
