{{- if and .Values.secrets .Values.debug.enableManualSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: party-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
