{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: party-secrets
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
