{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: party-client
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer }}
{{- end }}
spec:
  ingressClassName: nginx
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName:  party-client-tls
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: party-client
                port:
                  number: 80
{{- end }}
