apiVersion: v1
kind: Service
metadata:
  name: party-client
spec:
  selector:
    app: party-client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.client.port }}