global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'server'
    static_configs:
      - targets: ['server:3001']
    basic_auth:
      username: "admin"
      password: "admin"

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']