apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: party-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/william-wtr92/party
    targetRevision: main
    path: infra/helm/party
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: party
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
