apiVersion: v1
kind: Secret
metadata:
  name: github-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/william-wtr92/party
  username: YOUR_GITHUB_USERNAME
  password: YOUR_PERSONAL_ACCESS_TOKEN ## Repo permissions required for ArgoCD to access the repository

---

apiVersion: v1
kind: Secret
metadata:
  name: image-updater-git-writer
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  url: https://github.com/william-wtr92/party
  username: YOUR_GITHUB_USERNAME
  password: YOUR_PERSONAL_ACCESS_TOKEN ## Repo permissions + Write / Read package permissions required for ArgoCD Image Updater to write back updates
 