apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secretstore
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: eso-gcp-creds
            namespace: {{ .Values.eso.credentialsSecretNamespace }}
            key: credentials.json